# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Deep Research MCP
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package*.json tsconfig.json ./
COPY src ./src
RUN npm ci
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
COPY package*.json ./
COPY --from=builder /app/dist ./dist
RUN npm ci --only=production
ENV NODE_ENV=production
ENTRYPOINT ["node", "dist/index.js"]
